package com.kingdom.model.cards

enum class CardType {
    Action,
    ActionAttack,
    ActionAttackVictory,
    ActionAttackDuration,
    ActionAttackDurationVictory,
    ActionAttackLooter,
    ActionAttackLooterVictory,
    Victory,
    ActionReaction,
    ActionReactionVictory,
    Treasure,
    TreasureAttack,
    Curse,
    ActionVictory,
    TreasureVictory,
    ActionDuration,
    ActionDurationVictory,
    TreasureCurse,
    VictoryReaction,
    DurationVictory,
    TreasureReaction,
    ActionRuins,
    ActionShelter,
    ReactionShelter,
    VictoryShelter,
    ActionLooter,
    TreasureReserve,
    ActionReserve,
    ActionReserveVictory,
    ActionDurationReaction,
    ActionTraveller,
    ActionAttackTraveller,
    Event
}